### ISSUE TITLE
feat: make git author configurable in the GitStateStore

### ISSUE THREAD

**Issue by richcooper95** [syntasso/kratix#147]
Currently, we always use the Kratix service account in our Git commits. We should instead make this configurable.

![Image](https://github.com/syntasso/kratix/assets/58304039/955a3430-13b8-434b-8201-88ffc37e03e0)

### Details

- Create a `GitAuthor` struct and add it to the `GitStateStoreSpec`.
- Use it when setting up the Git writer in `git.go` [here](https://github.com/syntasso/kratix/blob/36b0515ba1b0aac20d434a8b79293a66a70b659d/lib/writers/git.go#L98) if it's present, and default to the Kratix service account if not.

**Comment by mrdavidlaing** [comment]
Having a static `GitAuthor` would be great.

Not sure if this is possible; but even better would be a dynamic `GitAuthor` based on the identity that change the promise resource-request.

ie - if user `alice@my-corp.com` ran `kubectl apply -f my-promise-request.yaml` then the commit to the GitStateStore would be attributed to `alice@my-corp.com`

That way commits to the GitStateStore become an audit log of who made which changes to the system without needing to enforce changes to the system going through a PR workflow that runs `kubectl apply -f my-promise-request.yaml`

**Comment by aclevername** [comment]
@mrdavidlaing 

> Having a static GitAuthor would be great.

We've just merged this feature #161 

> ie - if user alice@my-corp.com ran kubectl apply -f my-promise-request.yaml then the commit to the GitStateStore would be attributed to alice@my-corp.com
> That way commits to the GitStateStore become an audit log of who made which changes to the system without needing to enforce changes to the system going through a PR workflow that runs kubectl apply -f my-promise-request.yaml

Thats a great idea. Going to leave this issue open to track (cc @catmo-syntasso )

**Comment by kirederik** [comment]
we created https://github.com/syntasso/kratix/issues/162 to capture the request; we'll now really close this one
