### ISSUE TITLE
Update docker images to pull through scarf.sh (wait til oct1)

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix#199]
We want to integrate [scarf.sh](https://docs.scarf.sh/) into our installation scripts so that we can understand Kratix's usage.

We've got some packages generated already for the pipeline adapter: kratix.docker.scarf.sh/syntassodev/kratix-platform-pipeline-adapter
and platform: kratix.docker.scarf.sh/syntassodev/kratix-platform

We should replace these in Kratix.yaml and anywhere else we reference the docker images with the scarf versions.
**Note:** we aren't worried about the enterprise bundles for now, since we can track access to those by keys.

**Comment by SaphMB** [comment]
**Considerations to investigate**
1. Can we still refer to the images with a sha as we currently do with the docker image in the manifest? (e.g. `docker.io/syntasso/kratix-platform@sha256:79592f9c20a1c468b3da9021dbbcf7512f6b49c22b77f77e5cf4b275fae68401`
2. If so, does this have any impact on the metrics we get via scarf?

**Comment by catmo-syntasso** [comment]
There is a requirement on scarf to need a human readable version. They aren't sure if this is necessary, it doesn't seems to be super important on their side and they'll be in touch when its solved!

**Comment by catmo-syntasso** [comment]
Spoke to Arjun today, and he recommends getting the pixel implemented now. We won't track data, but it should do as soon as they ship the fix. If we do, we should double-check that people are still getting their downloads

**Comment by aclevername** [comment]
Updated Kratix release process to reference the images through scarf https://github.com/syntasso/kratix/pull/235

If I download the latest `kratix.yaml` I will see the scarf images:
```
cat ~/Downloads/kratix.yaml | grep scarf
  WC_IMG: syntasso.docker.scarf.sh/syntasso/kratix-platform-pipeline-adapter@sha256:d6d09c5a0e9c9e57b7f28bcc9aafe645b93b09d4c952b3a5b57c6209bf1d7030
        image: syntasso.docker.scarf.sh/syntasso/kratix-platform@sha256:d45b5e282dfa20ac81e3967ffa1ebc9f696960d9dc5ddb0ef4aafcec9624e212

```

**Comment by aclevername** [comment]
I deployed an instance of Kratix using new images, waiting for the metrics to appear for this request before closing

**Comment by aclevername** [comment]
Still no metrics for SHAs, only for tags
