### ISSUE TITLE
Internal CA issuer instead of Cert Manager

### ISSUE THREAD

**Issue by tdiaque** [syntasso/kratix#202]
While I am not too familiar with Cert Manager, I understand that you can utilize different issuers.

Is it possible to run Kratix without Cert Manager and instead use an internal CA for issuing certificates?

**Comment by catmo-syntasso** [comment]
Hi @tdiaque - very possible in theory. Leave it with us for now 👀

**Comment by aclevername** [comment]
Hi @tdiaque, yes you can use an internal CA with Kratix. Kratix's usage of cert-manager is minimal, we create a certificate for handling the authentication of a webhook with the k8s api. In the default setup we use cert-manager to:

1. Create an issuer
1. Create a certificate
1. Add the `caBundle` to the [validatingwebhookconfigurations](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#configure-admission-webhooks-on-the-fly)
1. Add the `caBundle` to the [validatingwebhookconfigurations](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#configure-admission-webhooks-on-the-fly)
1. Add the `caBundle` to the [CRD](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#service-reference)

To completely remove the dependency on cert-manager you can:
1. Remove the `Issuer` and `Certificate` resources in the `kratix.yaml` manifest
1. Manually fill in the `caBundle` fields that are being automatically set by cert-manager in the three resources mentioned above. 

An alternative is that you can configure cert-manager to use your [own issuer](https://cert-manager.io/docs/contributing/external-issuers/) when creating certificates, getting the same end-result as above but still leveraging cert-manager to inject the `caBundle` for you

**Comment by aclevername** [comment]
@tdiaque we've updated our docs with more detailed information on how to use Kratix without cert-manager https://docs.kratix.io/main/guides/installing-kratix-others#install-cert-manager

**Comment by tdiaque** [comment]
This is great! Thank you so much for the detailed information @aclevername
