### ISSUE TITLE
Labels for workflow pipelines

### ISSUE THREAD

**Issue by abangser** [syntasso/kratix#240]
In order to securely connect to Azure services from within Workflow pipelines users must both set an annotation on the service account used (see https://github.com/syntasso/kratix/issues/239) and set a label on the pipeline pod that is created by Kratix.

This story is to allow users to set labels on the pod spec created by the workflow pipelines. It will likely fit under the `spec` key in the `pipeline` kind (peer to `volumes`, `containers` and `imagePullSecrets` [here](https://docs.kratix.io/main/reference/workflows#pipelines)).

**Comment by kirederik** [comment]
So the workflow is of `kind: Pipeline` that, although not a CRD, it does include `metadata`.

What do you think about the following experience:

Promise definition:
![Image](https://github.com/user-attachments/assets/c86427cc-32df-474b-84f9-e777e75609db)

Promise Configure pod:
![Image](https://github.com/user-attachments/assets/16784e49-755c-4232-a3e8-3e4f42824331)

Resource Pod:
![Image](https://github.com/user-attachments/assets/74500f09-e23a-486b-835e-2ddf32feae55)


While there, I just added support for annotations as well

**Comment by kirederik** [comment]
Since we only create the job when we need to trigger a pipeline, the user won't get immediate feedback if they set a label with invalid values. I'll fix that by extending our webhook validation

**Comment by kirederik** [comment]
PR here: https://github.com/syntasso/kratix/pull/241

**Comment by Phiph** [comment]
Looks great! Thanks :)
