### ISSUE TITLE
feat: Support private github repos in Promise Releases

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix#242]
Customer comment in Kratix slack:
"I'm also working on using PromiseReleases in my setup so that I have a almost handsfree set up of kratix.
I've noticed that it can't read from private git repos - is there something I'm missing 🙂" - **there isn't!**

Currently Promise Releases only support public github repos. We had plans to expand this to other destinations (E.g. helm charts). In [this spike](https://github.com/syntasso/enterprise-kratix/issues/65), we evaluated the value of promise releases, and will be keeping them so we're happy to extend how they read promises.

```gherkin
Given I have a PromiseRelease
And the Promise referenced is in a private github repo
And I have provided the correct permissions in that repo
When I kaf the PromiseRelease
Then I should see the promise applied on my cluster

Given I have a PromiseRelease
And the Promise referenced is in a private github repo
And I have **not provided** the correct permissions in that repo
When I kaf the PromiseRelease
Then I should not see the promise applied on my cluster
And I should see the Promise in an "unavailable" status with details in the promise description
```

**Comment by abangser** [comment]
Work to be done:

- [X] Extend API to accept a secret
- [X] Pass authorization header through for http requests
- [ ] Systems test for auth'd endpoint (this will require extending the `release-test-hoster-image` server to have an auth'd endpoint)
- [ ] Document option
