### ISSUE TITLE
bug: PipelineCompleted condition momentarily set before all Pipelines have run

### ISSUE THREAD

**Issue by richcooper95** [syntasso/kratix#258]
## Summary

When `update-status` runs at the end of every successful Pipeline within a Configure workflow, we _always_ set the `PipelineCompleted` condition to `True` _for every Pipeline_.

When a Promise or Resource contains _multiple_ Pipelines in the Configure workflow, this no longer makes sense for two reasons:
1. `PipelineCompleted` is singular, and doesn't reflect the fact there may be multiple Pipelines.
2. The `PipelineCompleted` will be `True` for a short window between one Pipeline finishing and the next being triggered.

## Proposed fix

We should:
- Change the `PipelineCompleted` condition type to `ConfigureWorkflowCompleted` to better reflect what this condition is trying to convey.
- Update the condition's messages/reasons to reflect the possibility of multiple Pipelines.
- Only set the condition to `True` when the last Pipeline in a Configure workflow has completed successfully.

**Comment by ChunyiLyu** [comment]
release notes pending PR created: https://github.com/syntasso/kratix-docs/pull/141
