### ISSUE TITLE
Bug: secret "gitea-credentials" not found

### ISSUE THREAD

**Issue by woody1872** [syntasso/kratix#264]
On the guide to install Kratix on KinD there appears to be an issue on the [Set up State Store step](https://docs.kratix.io/main/guides/installing-kratix-others#set-up-state-store). It fails to setup Gitea because the secret "gitea-credentials" doesn't exist.

The [gitea-install.yaml](https://raw.githubusercontent.com/syntasso/kratix/main/hack/platform/gitea-install.yaml) file [references](https://raw.githubusercontent.com/syntasso/kratix/main/hack/platform/gitea-install.yaml#:~:text=valueFrom%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20secretKeyRef%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%3A-,gitea%2Dcredentials,-key%3A%20privateKey%0A%20%20%20%20%20%20%20%20%20%20%20%20%2D%20name) the  "gitea-credentials" secret but it doesn't yet exist.

There are no instructions which tell a user to create this secret, so I'm assuming it should be created for them?

Error:
```
$ kubectl --context=$PLATFORM get pods -n gitea
NAME                            READY   STATUS                            RESTARTS   AGE
gitea-5c965c46cb-5xnst          0/1     Init:CreateContainerConfigError   0          34s
gitea-create-repository-77n5l   0/1     Init:0/4                          0          24s

$ kubectl --context=$PLATFORM describe pod gitea-5c965c46cb-5xnst -n gitea
...
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  53s               default-scheduler  Successfully assigned gitea/gitea-5c965c46cb-5xnst to platform-control-plane
  Normal   Pulled     3s (x6 over 52s)  kubelet            Container image "gitea/gitea:1.21.11-rootless" already present on machine
  Warning  Failed     3s (x6 over 52s)  kubelet            Error: secret "gitea-credentials" not found
```

**Comment by richcooper95** [comment]
Hey @woody1872, thanks for bringing this to our attention! We've just fixed this and https://github.com/syntasso/kratix/issues/263 - you can find updated steps in the [installation instructions](https://docs.kratix.io/main/guides/installing-kratix-others#set-up-state-store).

The instructions now have an extra step to install the Gitea namespace and credentials:

```bash
bash <(curl -s https://raw.githubusercontent.com/syntasso/kratix/refs/heads/main/scripts/generate-gitea-credentials.sh)
```

Note that you will need to install the `gitea` CLI for this to work (required because the certs need to be generated dynamically).

Hope this helps!

**Comment by richcooper95** [comment]
Closing this as done, but please do let us know if you have any further issues @woody1872!
