### ISSUE TITLE
feat: include resource configure workflow results in the promise status

### ISSUE THREAD

**Issue by richcooper95** [syntasso/kratix#280]
## Context

The Promise does not currently convey any information about its resource requests. It would be useful to be able to read the status of the Resource Configure workflow for each resource request directly in the Promise status.

For example, rolling out a change to the Promise would cause the Resource Configure workflow to retrigger for every resource request. We would like to be able to just watch the status of the Promise to know which of these workflows have completed successfully, which have failed, and which are still in progress.

## Notes

- This could become very verbose if the Promise has many resource requests, so we should consider how to summarise the important information for users and highlight failures which may require user intervention.
- We would like to be able to programmatically monitor the status of all Resource Configure workflows, including those which have already succeeded. We could convey this extra information in a less human-readable form (e.g. a JSON string).
- Workflows may be triggered for a variety of reasons, so we also need to see the `LastTransitionTime` for the resource request's `ConfigureWorkflowCompleted` condition.

**Comment by SaphMB** [comment]
Following discussion with @aclevername and @richcooper95 on Friday, the planned approach (3) does not meet the objective that we required for this story. To be discussed further

**Comment by SaphMB** [comment]
Closing as we will not proceed with this as described, a new issue will be created the reflect the new strategy
