### ISSUE TITLE
Quickstart not installing namespace kratix-worker-system

### ISSUE THREAD

**Issue by jeremycaine** [syntasso/kratix#287]
Following this Quickstart guide [here](https://docs.kratix.io/main/guides/installing-kratix-others).

Maybe similar to [issue 282](https://github.com/syntasso/kratix/issues/282) from [agardnerIT](https://github.com/agardnerIT).

The issue is that the namespace `kratix-worker-system` has not been setup when checked at end of this Quickstart guide page.
I did notice that these yaml files - [this](https://raw.githubusercontent.com/syntasso/kratix/main/hack/destination/gitops-tk-resources.yaml) and [this](https://raw.githubusercontent.com/syntasso/kratix/main/config/samples/platform_v1alpha1_worker.yaml) - refer to `worker-1` so I modified the KIND worker cluster to be called that. However I have run these steps for it named `worker` and `worker-1` and same issue occurs.

Steps:
```
kind create cluster --image kindest/node:v1.27.3 --name platform
export PLATFORM="kind-platform"

kubectl --context $PLATFORM apply --filename https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.yaml

# check cert manager working before installing kratix
kubectl --context $PLATFORM get pods --namespace cert-manager

# install kratix on platform cluster
kubectl apply --context $PLATFORM --filename https://github.com/syntasso/kratix/releases/latest/download/kratix.yaml
kubectl --context $PLATFORM get pods -n kratix-platform-system

# Install MinIO and register it as a BucketStateStore
kubectl apply --context $PLATFORM --filename https://raw.githubusercontent.com/syntasso/kratix/main/config/samples/minio-install.yaml
kubectl apply --context $PLATFORM --filename https://raw.githubusercontent.com/syntasso/kratix/main/config/samples/platform_v1alpha1_bucketstatestore.yaml

kind create cluster --image kindest/node:v1.27.3 --name worker-1
export WORKER="kind-worker-1"

# install flux
kubectl apply --context $WORKER --filename https://raw.githubusercontent.com/syntasso/kratix/main/hack/destination/gitops-tk-install.yaml

# check working
kubectl --context $WORKER get pods --namespace flux-system

# Configure Flux to pull down from MinIO
kubectl apply --context $WORKER --filename https://raw.githubusercontent.com/syntasso/kratix/main/hack/destination/gitops-tk-resources.yaml

# Register the worker cluster as a Destination
kubectl apply --context $PLATFORM --filename https://raw.githubusercontent.com/syntasso/kratix/main/config/samples/platform_v1alpha1_worker.yaml

kubectl --context $WORKER get namespace kratix-worker-system
```
Issue occurs error returned:
```
Error from server (NotFound): namespaces "kratix-worker-system" not found
```
My environment:
```
# sw_vers
ProductName:		macOS
ProductVersion:		14.7
BuildVersion:		23H124
```

I am using **podman** not docker
```
# podman machine list
NAME                    VM TYPE     CREATED       LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default  applehv     7 months ago  Currently running  2           3.725GiB    93GiB
```
KIND
```
# kind get clusters
enabling experimental podman provider
platform
worker-1
```

**Comment by jeremycaine** [comment]
I created a single `quickstart` cluster. 
```
kind create cluster --image kindest/node:v1.27.3 --name quickstart
# set PLATFORM to point to the platform cluster context
export PLATFORM="kind-quickstart"
```

The same happens for the all in one [Quickstart](https://docs.kratix.io/main/quick-start) - again using `podman`.

```
...
 ~ kubectl get namespace kratix-worker-system
Error from server (NotFound): namespaces "kratix-worker-system" not found
```
Cluster list
```
~ kind get clusters
enabling experimental podman provider
platform
quickstart
worker-1
```

**Comment by shano** [comment]
Hi @jeremycaine 

Thanks for sharing this! I've just been looking into this issue. 

I can't reproduce your issue if I wait till all resources are available before proceeding to the next step, but I can reproduce this issue locally if I don't wait for cert-manager to install before installing kratix, so when you run:

`kubectl --context $PLATFORM apply --filename https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.yaml`

Do you wait until cert manager is available before installing kratix?

`kubectl apply --context $PLATFORM --filename https://github.com/syntasso/kratix/releases/latest/download/kratix.yaml`

Also, just to help with debugging, what OS are you running on? (thanks for trying with docker and podman!)

**Comment by jeremycaine** [comment]
Yes I wait until cert manager pods all show "running" before installing Kratix.
```
# check cert manager working before installing kratix
kubectl --context $PLATFORM get pods --namespace cert-manager
```
Is there another check that could be done on cert-manager? Perhaps it might report all pods running, but there is still some other initialisation going on?

At the moment I can only use `podman` on my work laptop. I will try and find an alternative environment to use 'docker'.
```
# sw_vers
ProductName:		macOS
ProductVersion:		14.7
BuildVersion:		23H124
```

**Comment by shano** [comment]
Thanks for the context! If you can find a docker environment, let me know if you continue to see this issue.

**Comment by jeremycaine** [comment]
Have you tried podman or just docker?

**Comment by shano** [comment]
At the moment, I haven’t tested the Quickstart guide with Podman, so it’s possible that some steps may not work as expected. That said, Podman support hasn’t been a common request from our community so far(I think you might be the first!).

If you uncover any further findings or issues as you experiment, please do share! It’s always super helpful feedback.

Let me know how you get on with Docker in an alternative environment, happy to assist further!

**Comment by jeremycaine** [comment]
I will see about using docker on my other laptop later today. 

Podman/OpenShift architecture is rootless user to increase security model which a lot of enterprise customers look for (I work for IBM who own Red Hat). When Kratix gets used in an enterprise environment more sophisticated security and opinionated deployment requirements like OpenShift might come up.

**Comment by shano** [comment]
Perfect, thanks @jeremycaine if I get time I'll have a look into the podman issues. If you uncover anything yourself though, do let us know!
