### ISSUE TITLE
clean up: consolidate kratix config

### ISSUE THREAD

**Issue by ChunyiLyu** [syntasso/kratix#294]
# Context

- We've recently introduced configmap `kratix` for people to customize kratix behavior: https://docs.kratix.io/main/reference/kratix-config/config
- This issue is about having a consolidated configmap for user configuration.
- WC_IMG is necessary as it's used in airgapped environments to point to internal registries.

## To do
- [ ] : remove the configmap `kratix-platform-wc-img-config`

This configmap is being created via kustomize in:
https://github.com/syntasso/kratix/blob/main/config/manager/kustomization.yaml#L17-L20
https://github.com/syntasso/kratix/blob/main/config/manager/wc-img-config.properties

- [ ] : set the default in kratix controller itself
- [ ] :  allows configuration of the work-creator image in configmap `kratix`

**Comment by SaphMB** [comment]
Be sure to update the helm charts

**Comment by SaphMB** [comment]
kratix-platform-wc-img-config contents:

```
apiVersion: v1
data:
  WC_IMG: docker.io/syntassodev/kratix-platform-pipeline-adapter:dev
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"WC_IMG":"docker.io/syntassodev/kratix-platform-pipeline-adapter:dev"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"kratix-manager","app.kubernetes.io/instance":"kratix-platform","app.kubernetes.io/part-of":"kratix"},"name":"kratix-platform-wc-img-config","namespace":"kratix-platform-system"}}
  creationTimestamp: "2024-12-13T12:21:14Z"
  labels:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-wc-img-config
  namespace: kratix-platform-system
  resourceVersion: "736"
  uid: fbf9a946-fb68-41cf-89bd-5957036de31d
```

**Comment by shano** [comment]
@catmo-syntasso 2 quick questions:

1. How does that new configmap look to you?
2. Should we actually worry about backward compatibility, or can we just tell customers to move the WC_IMG to the new configmap and things will break if they try to update?

**Comment by shano** [comment]
Actually, can I challenge the point of having WC_IMG as a configmap?

 If wc_img is just for internal use and we have no desire for customers to configure this, then why make it configurable and not just store this url in the code.

@ChunyiLyu / @SaphMB / @catmo-syntasso

**Comment by SaphMB** [comment]
Due the complexity that arises from ensuring the kratix configmap is kept up-to-date in the ske distribution, for now we will continue to maintain a separate configmap for the pipeline-adapter image but instead update this to refer to the 'pipeline-adapter' as opposed to the former name, wc-image

PR: https://github.com/syntasso/kratix/pull/305
