### ISSUE TITLE
feat: visibility to which pipeline corresponds to which promise/request

### ISSUE THREAD

**Issue by kirederik** [syntasso/kratix#84]
If Platform users make 3 requests and run `k get pods` i see:

```bash
k get pods
NAME                                   READY   STATUS              RESTARTS   AGE
configure-pipeline-redis-59614-ls9pd   0/1     Completed           0          14s
configure-pipeline-redis-5e5d7-vg9cl   0/1     Completed           0          7s
configure-pipeline-redis-80f23-fdvt2   0/1     Completed           0          21s
```

It's not possible to map the pipeline to the request.

It would be nice instead to see:
```
k get pods
NAME                                   READY   STATUS    RESTARTS   AGE
kratix-configure-redis-cat-5678        1/1     Running   0          12s
kratix-configure-redis-jake-1234       1/1     Running   0          20s
kratix-configure-redis-sapphire-9012   1/1     Running   0          3s
```

## Notes

* We will run into name length limits (63char), so this is a best-effort improvement.  consider more shorthand than `kratix-configure` to increase the likelihood of the new fitting. Viewings pods with labels `k get pods --show-labels` is still the best way to determine exactly what a pod is related to and is a k8s convention, ensure we have the right labels set.
* Do for all pipelines: [promise || resource] [configure || delete]

**Comment by aclevername** [comment]
would also be good to know what pipeline a pod corresponds to given we are adding support for multiple in #90

**Comment by catmo-syntasso** [comment]
To double confirm, the format will look like
`kratix-<pipelinetype>-<resource request kind>-<resource request metadata.name>-<UUID truncated when we reach 63 characters>`?

**Comment by aclevername** [comment]
I think with the work from #90 it would look more like this @catmo-syntasso 


`<some-prefix>-<promiseName>-<resourceName>-<pipelineName>-UUID`

e.g.

`kc-redis-jakes-create-tf-123ab`
`kratix-configure-redis-jakes-create-tf-123ab`
`kratix-redis-jakes-create-tf-123ab`

**Comment by catmo-syntasso** [comment]
‘kratix-app-as-a-service-my-new-service-create-tf-123ab’
I tried coming up with the longest version of my preferred combo and we’re still at 54 characters so I think we’re 🆒

**Comment by catmo-syntasso** [comment]
@richcooper95 and @kirederik to check if this has been implemented
